version: "3"
services:
  app:  
    restart: on-failure
    build: 
      dockerfile: dockerfile
      context: ./
    environment:
      DBHOST: $DBHOST
      NODE_ENV: production
      PORT: 4000
      DBUSER: $DBUSER
      DBPASS: $DBPASS
      POSTGRES_DB: students
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: sreTestApp
    volumes:
      - .:/app/
      - /app/node_modules

  web:
    restart: always
    build:
      dockerfile: web.dockerfile
      context: ./
    working_dir: /app
    volumes_from:
      - app
    ports:
     #- 4000:80
     - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: sreTestApp
  # seed postgres
  postgres:
    image: postgres:14
    environment:
      DBUSER: user
      DBPASS: pass

networks:
  default:
    name: sre-testapp_default