version: "3"
services:
  app:  
    restart: on-failure
    build: 
      dockerfile: dockerfile
      context: ./
    environment:
      DBHOST: $DBHOST
      NODE_ENV: production
      PORT: 4000
      DBUSER: $DBUSER
      DBPASS: $DBPASS
      POSTGRES_DB: students
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: sreTestApp
    volumes:
      - .:/app/
      - /app/node_modules

  web:
    restart: always
    build:
      dockerfile: web.dockerfile
      context: ./
    working_dir: /app
    volumes_from:
      - app
    ports:
     - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: sreTestApp
  # For seeding postgres
  postgres:
    build:
      dockerfile: dbseed.dockerfile
      context: ./
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: students
      USER: $USER
      PGPASSWORD: $PASS
      HOST: $DBHOST

networks:
  default:
    name: sre-testapp_default